### ISSUE TITLE
请问下，在命令行项目中如何启动？

### ISSUE THREAD

**Issue by lixsyulin** [wmchuang/EasyQuartz#1]
我在main函数中使用AddEasyQuartzService（），但是没有自动启动任务，是什么地方配置错误吗？
        static void Main(string[] args)
        {
            var builder = new ConfigurationBuilder()
               .SetBasePath(Directory.GetCurrentDirectory())
               .AddJsonFile("appsettings.json", optional: true, reloadOnChange: true)
               .AddEnvironmentVariables();
            IConfiguration Configuration = builder.Build();

            IServiceCollection serviceProvider = new ServiceCollection();
            serviceProvider.AddLogging();
            serviceProvider.AddSingleton<IConfiguration>(Configuration);
            serviceProvider.BuildServiceProvider();

            serviceProvider.AddEasyQuartzService();

            Console.ReadLine();
        }

    [TriggerCron("0/1 * * * * ? *")]
    public class Test1Job : IJob
    {
        public Task Execute(IJobExecutionContext context)
        {
            Console.WriteLine($"{DateTime.Now}我是  Test1Job");
            return Task.CompletedTask;
        }
    }

**Comment by wmchuang** [comment]
因为内部依赖了IHostedService, 所以需要创建个HostBuilder
![image](https://user-images.githubusercontent.com/25163291/90872776-b6a19680-e3cf-11ea-92ca-62a3903d116c.png)
